# Generated by Django 4.2.8 on 2023-12-24 16:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mainapp.customuser",
                    ),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("NW", "Networker"),
                            ("FS", "Freelancer Salesperson"),
                            ("FT", "Full-Time Salesperson"),
                        ],
                        default="NW",
                        max_length=2,
                    ),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                ("hobbies", models.TextField(blank=True, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_school_attended",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                ("work_experience", models.TextField(blank=True, null=True)),
                (
                    "sales_performance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "connections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobseeker_connections",
                        to="user_profile.jobseeker",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobseeker_projects",
                        to="user_profile.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("mainapp.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
